config/routes.rb
CodeTheChange::Application.routes.draw do
  devise_for :admin, :skip => [:registrations], :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  root 'pages#home'

  get '/about', to: 'pages#about'
  get '/projects', to: 'pages#projects'
  get '/course', to: 'pages#course'
  get '/sponsors', to: 'pages#sponsors'
  get '/admin', to: 'pages#admin'

  resources :sponsors

  namespace :admin do
    resources :terms, :events, :officers, :projects, :assignments

    resources :lessons do
      resources :lectures
      resources :tutorials
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :description, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_filter :authenticate_admin!

  def index
    @events = Event.all
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path
    else
      render 'new'
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(params[:event].permit(:title, :start_time, :end_time, :location, :description, :url))
      redirect_to admin_events_path
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    
    @event.destroy
    redirect_to admin_events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :start_time, :end_time, :location, :description, :url)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(params[:event].permit(:title, :start, :end, :location, :description, :url))
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :start, :end, :location, :description, :url)
    end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event] do |f| %>
  
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </p>

  <p>
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
 
  <p>
    <%= f.submit :class => "btn btn-default" %>
  </p>
  
<% end %>

app/views/admin/events/edit.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li><%= link_to "Events", admin_events_path %></li>
      <li><%= link_to "Event", admin_event_path(@event) %></li>
      <li class="active">Edit</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>Edit Event</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/admin/events/index.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li class="active">Events</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>Events</h2>

    <p>
      <%= link_to 'New Event', new_admin_event_path, { class: "btn btn-default" } %>
    </p>

    <table class="table">
      <tr>
        <th>Title</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Location</th>
        <th>Description</th>
        <th>URL</th>
        <th>Actions</th>
      </tr>
     
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.start_time.strftime("%A, %B %d, %I:%M%p") %></td>
          <td><%= event.end_time.strftime("%A, %B %d, %I:%M%p") %></td>
          <td><%= event.location %></td>
          <td><%= event.description %></td>
          <td><%= event.url %></td>
          <td><%= link_to 'Show', admin_event_path(event) %> | 
              <%= link_to 'Edit', edit_admin_event_path(event) %> | 
              <%= link_to 'Destroy', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li><%= link_to "Events", admin_events_path %></li>
      <li class="active">New</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>New Event</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/admin/events/show.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li><%= link_to "Events", admin_events_path %></li>
      <li class="active">Event</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>Event Details</h2>

    <p>
      <strong>Title:</strong>
      <%= @event.title %>
    </p>
     
    <p>
      <strong>Start Time:</strong>
      <%= @event.start_time.strftime("%A, %B %d, %I:%M%p") %>
    </p>

    <p>
      <strong>End Time:</strong>
      <%= @event.end_time.strftime("%A, %B %d, %I:%M%p") %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>URL:</strong>
      <%= @event.url %>
    </p>

    <%= link_to 'Edit', edit_admin_event_path(@event), { class: "btn btn-default" } %>
  </div>
</div>