config/routes.rb
CodeTheChange::Application.routes.draw do
  devise_for :admin, :skip => [:registrations], :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  root 'pages#home'

  get '/about', to: 'pages#about'
  get '/projects', to: 'pages#projects'
  get '/course', to: 'pages#course'
  get '/sponsors', to: 'pages#sponsors'
  get '/admin', to: 'pages#admin'

  resources :sponsors

  namespace :admin do
    resources :terms, :events, :officers, :projects, :assignments

    resources :lessons do
      resources :lectures
      resources :tutorials
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :term
  
  validates :organization, presence: true
  validates :description, presence: true

  has_attached_file :image, 
    :styles => { :thumbnail => "120x90>", :small => "200x150>", :medium => "500x375>" }, 
    :default_url => "/images/projects/missing.png",
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  before_filter :authenticate_admin!

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to admin_projects_path
    else
      render 'new'
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(params[:project].permit(:organization, :description, :url, :image, :term_id))
      redirect_to admin_projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    
    @project.destroy
    redirect_to admin_projects_path
  end

  private
    def project_params
      params.require(:project).permit(:organization, :description, :url, :image, :term_id)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(params[:project].permit(:organization, :description, :url))
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:organization, :description, :url)
    end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :term_id %><br>
    <%= f.select :term_id, Term.all.collect { |term| [ term.season + " " + term.year.to_s, term.id ] } %>
  </p>
 
  <p>
    <%= f.submit :class => "btn btn-default" %>
  </p>
  
<% end %>

app/views/admin/projects/edit.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li><%= link_to "Projects", admin_projects_path %></li>
      <li><%= link_to "Project", admin_project_path(@project) %></li>
      <li class="active">Edit</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>Edit Project</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/admin/projects/index.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li class="active">Projects</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>Projects</h2>
     
    <p>
      <%= link_to 'New Project', new_admin_project_path, { class: "btn btn-default" } %>
    </p>

    <table class="table">
      <tr>
        <th>Organization</th>
        <th>Description</th>
        <th>URL</th>
        <th>Image</th>
        <th>Term</th>
        <th>Actions</th>
      </tr>
     
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.organization %></td>
          <td><%= project.description %></td>
          <td><%= project.url %></td>
          <td><%= image_tag project.image.url(:thumbnail) %></td>
          <td><%= Term.find(project.term_id).season + " " + Term.find(project.term_id).year.to_s %></td>
          <td><%= link_to 'Show', admin_project_path(project) %> | 
              <%= link_to 'Edit', edit_admin_project_path(project) %> | 
              <%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/projects/new.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li><%= link_to "Projects", admin_projects_path %></li>
      <li class="active">New</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>New Project</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/admin/projects/show.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li><%= link_to "Admin", admin_path %></li>
      <li><%= link_to "Projects", admin_projects_path %></li>
      <li class="active">Project</li>
    </ol>
  </div>
</div>

<div class="section">
  <div class="container">
    <h2>Project Details</h2>

    <p>
      <strong>Organization:</strong>
      <%= @project.organization %>
    </p>
     
    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>

    <p>
      <strong>URL:</strong>
      <%= @project.url %>
    </p>

    <p>
      <strong>Image:</strong>
      <%= image_tag @project.image.url(:medium) %>
    </p>

    <%= link_to 'Edit', edit_admin_project_path(@project), { class: "btn btn-default" } %>
  </div>
</div>