config/routes.rb
CodeTheChange::Application.routes.draw do
  devise_for :admin, :skip => [:registrations], :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  root 'pages#home'

  get '/about', to: 'pages#about'
  get '/projects', to: 'pages#projects'
  get '/course', to: 'pages#course'
  get '/sponsors', to: 'pages#sponsors'
  get '/admin', to: 'pages#admin'

  resources :sponsors

  namespace :admin do
    resources :terms, :events, :officers, :projects, :assignments

    resources :lessons do
      resources :lectures
      resources :tutorials
    end
  end

end

app/views/pages/_event.html.erb
<div class="event row">
  <div class="col-xs-1 date-wrapper">
    <p class="date">
      <span class="month"><%= event.start_time.strftime("%b") %></span>
      <span class="day"><%= event.start_time.strftime("%d") %></span>
    </p>
  </div>
  <div class="col-xs-11">
    <h4 class="title"><%= link_to event.title, event.url, target: "_blank" %></h4>
    <p>
      <span class="time">
        <span class="glyphicon glyphicon-time"></span>
        <%= event.start_time.strftime("%I:%M%p") %> - <%= event.end_time.strftime("%I:%M%p") %>
      </span>
      <span class="location">
        <span class="glyphicon glyphicon-map-marker"></span>
        <%= event.location %>
      </span>
    </p>
    <p>
      <%= event.description %>
    </p>
  </div>
</div>

app/views/pages/_officer.html.erb
<li>
  <div class="ch-item" style="background-image:url('<%= officer.image.url(:medium) %>')">
    <div class="ch-info">
      <h3><%= officer.name %></h3>
      <p><%= officer.position %></p>
    </div>
  </div>
</li>

app/views/pages/_project_modal.html.erb
<div class="modal fade" id=<%= project.id.to_s + "-modal" %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><%= project.organization %></h4>
      </div>
      <div class="modal-body project-body">
        <p class="description">
          <%= project.description %>
        </p>
        <% if project.url != "" %>
          <p>
            <%= link_to project.url, project.url, target: "_blank" %>
          </p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/_syllabus.html.erb
<div class="syllabus">
  <h2>Syllabus</h2>
  <h4>Basic Information</h4>
  <table class="table table-bordered">
    <tr>
      <td>Facilitator</td>
      <td>Michael Lannin</td>
    </tr>
    <tr>
      <td>Instructor of Record</td>
      <td>Pieter Abbeel</td>
    </tr>
    <tr>
      <td>Number of Units</td>
      <td>2 Units</td>
    </tr>
    <tr>
      <td>Time &amp; Location</td>
      <td>Monday, 6:00pm to 8:00pm, 405 Soda</td>
    </tr>
    <tr>
      <td>Suggested Prerequisite</td>
      <td>CS 61A</td>
    </tr>
  </table>
  <h4>Course Overview and Overview</h4>
  <p><strong>Description:</strong> This course aims to teach students web technologies by working on real­world projects with non­profit and social­sector partners. The first part of this class will be geared towards covering basic web development topics and providing resources for more advanced learning. In the second part of the class, students will work in small teams to implement high­impact projects for partner organizations.
  <p><strong>Suggested Prerequisite:</strong> We recommend that students complete CS 61A prior to this class. Students are expected to have prior programming experience but web application experience is not mandatory. The class will be open to students of all years and we will be encouraging teams of people with mixed experience so that beginners can learn from people with more experience. Enrollment Requirements: Students are required to submit an application and attend the first class.</p>
  <p><strong>Objectives:</strong> By the end of the course, students should:
    <ul>
      <li>Have a solid understanding of web development technologies</li>
      <li>Be aware of more complex web technologies and have resources for learning them</li>
      <li>Have completed a web development project for a nonprofit organization</li>
    </ul>
  </p>
  <h4>Grading</h4>
  <p><strong>Percentage Breakdown:</strong> Your grade in the class will be based on six assignments, a final project and presentation, and participation and attendance. The following percentages will determine the makeup of your grade:
    <ul>
      <li>Each assignment will be worth 5% each</li>
      <li>The final project and presentation will be worth 50%</li>
      <li>Participation and attendance will be worth 20%</li>
    </ul>
  </p>
  <p><strong>Assignments:</strong> The first part of the class will be centered around learning. During this section of the course, homeworks will be assigned as a means to test students’ understanding of the material covered in the class.
  <p><strong>Final Project and Presentation:</strong> The second part of the class will be focused on the implementation of a project for a nonprofit organization. The goal is to create something that students can hand off to the organization at the end of the semester. Students will be expected to give a presentation on their project on the last day of class.</p>
  <p><strong>Participation and Attendance:</strong> Given that there is only one class meeting per week and that collaboration with other students is crucial, attendance and participation is very important. We expect students to attend all class sessions unless they get an absence excused.</p>
  <h4>Additional Information</h4>
  <p><strong>Lightning Talks:</strong> Once the project portion of the class has begun, student teams will give lightning talks each class. In these talks, they will give quick (1­2 minute) updates on their projects to everyone in the class. This will help students learn what other teams are doing and stay accountable.</p>
  <p><strong>Outside Work:</strong> Much of the work will be done outside of class time. However, many issues in web development are best solved as a team. Thus, class time is great for debugging as a group, pair programming, or getting help from the instructors.</p>
</div>

app/views/pages/about.html.erb
<% title "About" %>
<% description "Code the Change is an organization that empowers computer scientists to use their technical skills for social good through non-profit projects." %>

<div class="about">
  <div class="container">
    <h2>About Us</h2>
    <div class="row">
      <div class="col-md-7">
        <p>Code the Change is an organization that empowers computer scientists to use their technical skills for social good through non-profit projects.</p>
        <p>The Berkeley chapter consists of two divisions. Our project teams work on more challenging projects for nonprofits, and consist of more experienced developers. Our DeCal program, Web Development for Nonprofits, is intended for students with less experience in computer science; it offers them a chance to learn web development while working on a project for a nonprofit organization. Our members are comprised of Cal students with a passion for both technology and the social sector. We offer a unique opportunity to improve your technical abilities and form meaningful relationships with members who share similar interests.</p>
        <p>To learn more about the Stanford chapter and Code the Change as a national organization, please visit <%= link_to "codethechange.org", "https://codethechange.org/", target: "_blank" %></p>
        <p>If you represent a nonprofit organization and are interested in our technical services, please email us at <%= mail_to "berkeley@codethechange.org" %>.
      </div>
      <div class="col-md-5">
        <%= image_tag "https://dl.dropboxusercontent.com/u/280319558/images/samking-clinton-2012-03-30.jpg", class: "img-thumbnail img-responsive img-about" %>
      </div>
    </div>
  </div>
</div>

<% unless @officers.length == 0 %>
  <hr>

  <div class="officers">
    <div class="container">
      <h2>Officers</h2>
      <ul class="ch-grid">
        <% if @president %>
          <%= render 'pages/officer', :officer => @president %>
        <% end %>
        <% if @vp_of_projects %>
          <%= render 'pages/officer', :officer => @vp_of_projects %>
        <% end %>
        <% if @vp_of_development %>
          <%= render 'pages/officer', :officer => @vp_of_development %>
        <% end %>
        <% if @vp_of_operations %>
          <%= render 'pages/officer', :officer => @vp_of_operations %>
        <% end %>
        <% @project_managers.each do |project_manager| %>
          <%= render 'pages/officer', :officer => project_manager %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/pages/admin.html.erb
<% title "Admin" %>

<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <li class="active">Admin</li>
    </ol>
  </div>
</div>

<div class="admin">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h3>Events</h3>
        <p><%= link_to 'New Event', new_admin_event_path, { class: "btn btn-default" } %><%= link_to 'View all events', admin_events_path, { class: "view" } %></p>
        <hr>
        <h3>Officers</h3>
        <p><%= link_to 'New Officer', new_admin_officer_path, { class: "btn btn-default" } %><%= link_to 'View all officers', admin_officers_path, { class: "view" } %></p>
        <hr>
      </div>
      <div class="col-md-6">
        <h3>Projects</h3>
        <p><%= link_to 'New Project', new_admin_project_path, { class: "btn btn-default" } %><%= link_to 'View all projects', admin_projects_path, { class: "view" } %></p>
        <hr>
        <h3>Terms</h3>
        <p><%= link_to 'New Term', new_admin_term_path, { class: "btn btn-default" } %><%= link_to 'View all terms', admin_terms_path, { class: "view" } %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% title "Home" %>
<% description "Code the Change helps computer scientists use their skills to make social change an integral part of computer science culture." %>

<div class="hero">
  <div class="container">
    <%= image_tag "https://dl.dropboxusercontent.com/u/280319558/images/code-the-change-logo-with-text.png", class: "img-responsive" %>
    <p class="lead">We help computer scientists use their skills to make social change an integral part of computer science culture.</p>
  </div>
</div>

<div class="callout">
  <div class="container">
    Are you a nonprofit organization in need of technical help? Please email us at <%= mail_to "berkeley@codethechange.org" %>
  </div>
</div>

<div class="divisions">
  <div class="container">
    <div class="row division">
      <div class="col-sm-4 col-md-3 col-md-offset-1">
        <%= image_tag "https://dl.dropboxusercontent.com/u/280319558/images/projects-icon.png", class: "img-responsive img-division" %>
      </div>
      <div class="col-sm-8 col-md-7">
        <h3>Projects</h3>
        <p>The Berkeley chapter focuses on forming project teams to assist nonprofits in achieving their goals, whether it be through web development or mobile app design. Our project teams offer an opportunity for computer scientists with more experience to work on more robust projects for nonprofit organizations. If you would like to join one of our project teams, please fill out our application!</p>
      </div>
    </div>
    <div class="row division">
      <div class="visible-xs">
        <%= image_tag "https://dl.dropboxusercontent.com/u/280319558/images/decal-icon.png", class: "img-responsive img-division" %>
      </div>
      <div class="col-sm-8 col-md-7 col-md-offset-1">
        <h3>Course</h3>
        <p>We are partnered with the Web Development for Nonprofits DeCal. This course aims to teach students web technologies by working on real-world projects with nonprofit and social-sector partners. We hope that this course will attract computer scientists with less experience to contribute their skills to the nonprofit space. If you are interested in the DeCal, you can learn more at <%= link_to "www.webdevfornonprofits.org", "http://www.webdevfornonprofits.org/", target: "_blank" %>.</p>
      </div>
      <div class="col-sm-4 col-md-3 hidden-xs">
        <%= image_tag "https://dl.dropboxusercontent.com/u/280319558/images/decal-icon.png", class: "img-responsive img-division" %>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="events">
  <div class="container">
    <h2>Events</h2>
    <h3 class="subheader">Upcoming Events</h3>
    <% if @upcoming_events.length == 0 %>
      <p class="message">There are currently no upcoming events.</p>
    <% end %>
    <% @upcoming_events.each do |upcoming_event| %>
      <%= render 'pages/event', :event => upcoming_event %>
    <% end %>
    <h3 class="subheader">Past Events</h3>
    <% @past_events.each do |past_event| %>
      <%= render 'pages/event', :event => past_event %>
    <% end %>
  </div>
</div>

app/views/pages/projects.html.erb
<% title "Projects" %>
<% description "The Berkeley chapter focuses on forming project teams to assist non-profits in achieving their goals, whether it be through web development or mobile app design." %>

<div class="projects">
  <div class="container">
    <h2>Projects</h2>
    <% @terms.each do |term| %>
      <h3 class="subheader"><%= term.season + " " + term.year.to_s %></h3>
      <div class="row project-row">
        <% term.projects.each do |project| %>
          <div class="col-md-3 col-sm-4 project-wrapper" data-toggle="modal" data-target=<%= "#" + project.id.to_s + "-modal" %>>
            <div class="project">
              <div class="project-image">
                <span class="helper"></span>
                <%= image_tag project.image.url(:small), class: "img-thumbnail img-responsive img-project" %>
              </div>
              <div class="project-info"><%= project.organization %></div>
            </div>
          </div>
          <%= render 'pages/project_modal', :project => project %>
        <% end %>  
      </div>
    <% end %>
  </div>
</div>

app/views/pages/sponsors.html.erb
<% title "Sponsors" %>

<div class="sponsors">
  <div class="container">
    <h2>Sponsorship Packages</h2>
    <p>Thank you for showing interest in becoming a sponsor of Code the Change! Please contact us at <%= mail_to "berkeley@codethechange.org" %> if you have any questions about becoming a sponsor.</p>
    <div class="row">
      <div class="col-md-4">
        <h3><span class="label label-default label-bronze">Bronze</span>&nbsp;$250</h3>
        <p>Includes company logo on our sponsor page and resume book.</p>
      </div>
      <div class="col-md-4">
        <h3><span class="label label-default label-silver">Silver</span>&nbsp;$500</h3>
        <p>Includes one on-campus informational session or workshop, company logo on sponsor page, and resume book.</p>
      </div>
      <div class="col-md-4">
        <h3><span class="label label-default label-gold">Gold</span>&nbsp;$1000</h3>
        <p>Includes multiple on-campus informational sessions / workshops / events, company logo on sponsor page, and resume book.</p>
      </div>
    </div>
    <p class="instructions">For instructions on how to donate to Code the Change, <%= link_to "click here", "https://dl.dropboxusercontent.com/u/280319558/sponsorship-instructions.pdf", target: "_blank" %>
  </div>
</div>