config/routes.rb
CodeTheChange::Application.routes.draw do
  devise_for :admin, :skip => [:registrations], :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  root 'pages#home'

  get '/about', to: 'pages#about'
  get '/projects', to: 'pages#projects'
  get '/course', to: 'pages#course'
  get '/sponsors', to: 'pages#sponsors'
  get '/admin', to: 'pages#admin'

  resources :sponsors

  namespace :admin do
    resources :terms, :events, :officers, :projects, :assignments

    resources :lessons do
      resources :lectures
      resources :tutorials
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer" role="contentinfo">
  <div class="container">
    <p>&copy; <%= Time.now.year %> Code the Change</p>
    <ul class="footer-links">
      <li><%= mail_to "berkeley@codethechange.org", "Email" %></li>
      <li class="muted">&middot;</li>
      <li><%= link_to "Facebook", "https://www.facebook.com/ctcberkeley" %></li>
      <li class="muted">&middot;</li>
      <li><%= link_to "GitHub", "https://github.com/ctcberkeley" %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top ctc-navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
        <li class="<%= 'active' if current_page?(projects_path) %>"><%= link_to "Projects", projects_path %></li>
        <li class="<%= 'active' if current_page?(sponsors_path) %>"><%= link_to "Sponsors", sponsors_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li class="<%= 'active' if current_page?(admin_path) %>"><%= link_to "Admin", admin_path %></li>
          <li><%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %></li>
        <% else %>
          <li class="<%= 'active' if current_page?(new_admin_session_path) %>"><%= link_to "Sign In", new_admin_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="messages">
      <div class="container">
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Code the Change" %>">
    <%= csrf_meta_tags %>

    <title><%= content_for?(:title) ? yield(:title) + " | Code the Change" : "Code the Change" %></title>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="main">
      <%= render 'layouts/messages' %>
      
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>